version: '3'

services:

  flask_app:
    build: ./flask_template
    restart: always
    
    ports:
      - "5000:5000"
      - "50001:50001"
    
    volumes:
      - ./flask_template:/usr/src/app

